### ISSUE TITLE
Ошибка в получении отметок Zenless Zone Zero

### ISSUE THREAD

**Issue by JennyTim** [NatsumeAoii/Hoyolab-AutoSign#1]
Работают отметки в Genshin Impact, Honkai: Star Rail и Honkai Impact 3rd, но в Zenless Zone Zero в телеграм боте ошибка 
活动已结束 (-500012)
![image](https://github.com/user-attachments/assets/114f2933-a8c7-444b-bf65-52b8c115f6e0)

**Comment by NatsumeAoii** [comment]
will try to fix next week!, thank for ur report!

**Comment by NatsumeAoii** [comment]
yo!, i know its very late but i already update it. enjoy

**Comment by JennyTim** [comment]
> yo!, i know its very late but i already update it. enjoy

Thank you!
